/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package junit.jupiter;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    void reverseStringTest(){
        Demo d1 = new Demo();
        assertEquals("hannah",d1.reverseString("annah"));
    }
}
