/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package junit.jupiter;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Demo d1 = new Demo();
        String reversedString = d1.reverseString("Data");        
    }
}
